name: Build and Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.17
    - run: npm install
    - run: git config --global user.email "ktmcguire@sandiego.edu"
    - run: git config --global user.name "Kathleen McGuire"
    - run: export NODE_OPTIONS=--openssl-legacy-provider && export CI=false && npm run deploy

  